### ISSUE TITLE
Imported test cases are truncated!

### ISSUE THREAD

**Issue by bendrissou** [AFLplusplus/AFLplusplus#2184] opened 2024-08-12 11:10 UTC
Hi,

When syncing AFL++ with Nautilus, the imported test cases are slightly truncated, and so their structure is broken. I would like to ask what's the reason of truncating these test case, and is there a way to instruct AFL to import the test cases unchanged?

Note: This issue persists even with `AFL_DISABLE_TRIM=1`. So, I don't think the trimming function is the culprit here.

**Comment by bendrissou** [comment] 2024-08-12 12:40
I think the reason is that the post-processing function changes the size of the file, but the original file size is maintained, when writing the test case.

**Comment by bendrissou** [comment] 2024-08-12 13:04
Solved by saving the original test case to queue after executing post_process.

**Comment by vanhauser-thc** [comment] 2024-08-12 13:19
If you have trim disabled then this should not happen.Please provide concrete steps to reproduce, especially inputs.Am 12.08.2024 um 13:11 schrieb Bachir Bendrissou ***@***.***>:﻿
Hi,
When syncing AFL++ with Nautilus, the imported test cases are slightly truncated, and so their structure is broken. I would like to ask what's the reason of truncating these test case, and is there a way to instruct AFL to import the test cases unchanged?
Note: This issue persists even with AFL_DISABLE_TRIM=1. So, I don't think the trimming function is the culprit here.

**Comment by vanhauser-thc** [comment] 2024-08-12 13:22
> Solved by saving the original test case to queue after executing post_process.

The result of post process should be saved

**Comment by bendrissou** [comment] 2024-08-13 11:00
It's not straightforward to reproduce this. I am using a modified version of AFL++ alongside Nautilus, and some grammar file.

**Comment by vanhauser-thc** [comment] 2024-08-16 08:47
I just fixed a bug where what you saw would happen if also a custom send function was used.

if that is not what is happening in your case then please verify your issue first with an unmodified afl++ ...

**Comment by vanhauser-thc** [comment] 2024-08-20 10:43
closing this for now, please reopen if you can reproduce it with current afl++ dev state :)

**Closed as completed by vanhauser-thc** 2024-08-20 10:43 UTC
